# Generated by Django 4.0.2 on 2022-02-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.IntegerField(max_length=14)),
                ('token', models.IntegerField()),
                ('razao_social', models.CharField(max_length=150, verbose_name='Razão')),
                ('conta', models.IntegerField(max_length=50)),
                ('rua', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('numero', models.IntegerField(max_length=8)),
                ('complemento', models.IntegerField(max_length=200)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.IntegerField(max_length=8)),
            ],
        ),
    ]
